server:
  port: 10010

spring:
  application:
    name: gateway #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos单机地址
    gateway:
      routes:
        #网关路由配置
        - id: user-service-rule #路由id，自定义，唯一即可
          uri: lb://user-service #路由的目标地址，lb = loadBalance 后面跟服务名称
          predicates: #路由断言，
            - Path=/user/** #路径匹配，/user/规则

        - id: order-service-rule
          uri: lb://order-service
          predicates:
            - Path=/order/**