server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud-it?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #在注册中心的应用名称 写在bootstrap中了，
#  application:
#    name: user-service
  cloud:
    nacos:
      discovery:
        #nginx80端口代理到 到 nacos_cluster 8843/8845/8847
        #server-addr: 127.0.0.1:80
        #server-addr: localhost:8848 #暂时改为单机nacos 写在bootstrap中了，

        #配置nacos集群
        cluster-name: SH
    #sentinel的配置，指定dashboard端口
    sentinel:
      transport:
        dashboard: localhost:8080
      #关闭sentinel懒加载
      eager: false
mybatis:
  type-aliases-package: com.chen.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.chen: debug
  pattern:
    dateformat: HH:mm:ss:SSS
#chen:
#  gender: male