server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud-it?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.chen.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.chen: debug
  pattern:
    dateformat: HH:mm:ss:SSS