server:
  port: 10010
spring:
  application:
    name: sys-gateway #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos单机地址
    gateway:
      routes:
        #网关路由配置
        - id: user-service-rule #路由id，自定义，唯一即可
          uri: lb://user-service #路由的目标地址，lb = loadBalance 后面跟服务名称
          predicates: #路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/**,/config/** #路径匹配，，只要以/user/开头就符合规则
        #例如 浏览器访问localhost:10010/user/101 就可以按照localhost:8081或者8082或者8083/user/{id}这个规则访问

        - id: order-service-rule
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: security-auth
          uri: lb://sys-security-oauth
          predicates:
            - Path=/auth/**
      #添加一个过滤器(默认过滤器，上面两个网关路由都会触发这个过滤器，调用通过order-service——————>user-service，order会触发，user-service不会触发)，添加请求头
#      default-filters:
#        - AddRequestHeader=Token, 1299117865
