server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud-it?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #服务注册名称
  application:
    name: order-service
    #注册消费者
  cloud:
    nacos:
      discovery:
        #nginx80端口代理到 到 nacos_cluster 8843/8845/8847
        #server-addr: localhost:80
        server-addr: localhost:8848 #暂时改为单机nacos
        cluster-name: HZ
        #环境隔离: nacos命名空间id，不同namespace，相互隔离，不能访问其他namespace实例
#        namespace: 3182f621-4c39-4cec-8f26-b831de368b8f
mybatis:
  type-aliases-package: com.chen.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.chen: debug
  pattern:
    dateformat: HH:mm:ss:SSS
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
#feign性能优化，URLConnection：默认实现，不支持连接池，可以更改为Apache HttpClient/OKHttp,这两者支持连接池
    #优化二：日志级别更改为Basic
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载,让请求加载更快
    clients: # 指定饥饿加载的服务名称
      - user-service
feign:
  client:
    config:
      default: # default全局的配置
        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
