spring:
  application:
    name: sys-security-oauth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springcloud-auth?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: root
  redis:
    database: 2
    host: localhost
    port: 6379
server:
  port: 8090